import argparse


def str2bool(v):
    if isinstance(v, bool):
        return v
    v = str(v).strip().lower()
    if v in ('true', '1', 'yes', 'y', 't'):
        return True
    if v in ('false', '0', 'no', 'n', 'f'):
        return False
    raise argparse.ArgumentTypeError(f"Invalid boolean value: {v}")


def parse_opts():
    parser = argparse.ArgumentParser()
    arguments = {
        'dataset': [
            dict(name='--datasetName',
                 type=str,
                 default='sims',
                 help='mosi, mosei, sims or simsv2'),
            dict(name='--dataPath',
                 default="/18T/yechenlu/MSA_datasets/SIMS/Processed/unaligned_39.pkl",
               # default="/18T/yechenlu/MSA_datasets/SIMS/Processed/unaligned_39_roberta.pkl",
                 type=str,
                 help=' '),
            dict(name='--seq_lens',
                 default=[50, 55, 400],
                 type=list,
                 help='the length of T, V, A modalities; sims/simsv2: [50, 55, 400] (text from BERT len); mosi/mosei: []'),
            dict(name='--fea_dims',
                 default=[768, 177, 25],
                 type=list,
                 help='feature dims of T, V, A; sims/simsv2: [768, 177, 25]; mosi/mosei: [768, 709, 33]'),
            dict(name='--num_workers',
                 default=8,
                 type=int,
                 help=' '),
            dict(name='--train_mode',
                 default="regression",
                 type=str,
                 help=' '),
        ],

        'network': [
            dict(name='--model_type',
                 default='pid_dualpath',
                 type=str,
                 help='Model: kmsa (default) or pid_dualpath for Route B dual-path'),
            dict(name='--fusion_layers',
                 default=3,
                 type=int),
            dict(name='--dropout',
                 default=0.4,
                 type=float),
            dict(name='--fusion_dropout',
                 default=0.4,
                 type=float,
                 help='Dropout at F_final fusion point (0.3~0.5 for strong regularization)'),
            dict(name='--head_dropout',
                 default=0.4,
                 type=float,
                 help='Dropout in MLP prediction head layers (0.3~0.5)'),
            dict(name='--hidden_size',
                 default=256,
                 type=int),
            dict(name='--ffn_size',
                 default=512,
                 type=int),
            # Phase 2: Conflict-JS参数
            dict(name='--senti_num_classes',
                 default=7,
                 type=int,
                 help='Number of sentiment classes for posterior distribution'),
            dict(name='--tau_conf',
                 default=0.3,
                 type=float,
                 help='Threshold for conflict evidence (sentiment difference)'),
            dict(name='--tau_con',
                 default=0.1,
                 type=float,
                 help='Threshold for congruent evidence (sentiment difference)'),
            dict(name='--tau_rel',
                 default=0.5,
                 type=float,
                 help='Threshold for confidence (reliability)'),
            dict(name='--rel_min',
                 default=0.05,
                 type=float,
                 help='Minimum reliability for valid tokens in EvidenceSplitter'),
            dict(name='--conf_ratio',
                 default=0.25,
                 type=float,
                 help='Conflict evidence percentile (top conf_ratio)'),
            dict(name='--con_ratio',
                 default=0.25,
                 type=float,
                 help='Congruent evidence percentile (bottom con_ratio)'),
            dict(name='--evidence_split_mode',
                 default='topk',
                 type=str,
                 help='EvidenceSplitter strategy: topk (quota by d) or quantile (original)'),
            dict(name='--min_conf_k',
                 default=4,
                 type=int,
                 help='Min number of conflict tokens per sample in topk mode'),
            dict(name='--min_con_k',
                 default=4,
                 type=int,
                 help='Min number of congruent tokens per sample in topk mode'),
            dict(name='--gate_k',
                 default=8.0,
                 type=float,
                 help='Gate gain for alpha_m (Step2: 10.0->8.0 使门控更平滑)'),
            dict(name='--gate_tau',
                 default=0.12,
                 type=float,
                 help='Gate threshold for conflict routing (Step2: 0.15->0.12 更容易触发冲突分支)'),
            # Token筛选参数
            dict(name='--use_vision_pruning',
                 default=True,
                 type=str2bool,
                 help='Whether to use vision token pruning'),
            dict(name='--iec_mode',
                 default='text_guided',
                 type=str,
                 help='IEC mode: text_guided (prune+merge) or heuristic (DART)'),
            dict(name='--vision_keep_ratio',
                 default=0.50,
                 type=float,
                 help='Vision token keep ratio for TextGuidedPruner'),
            dict(name='--vision_target_ratio',
                 default=0.6,
                 type=float,
                 help='Vision token retention ratio (heuristic mode)'),
            # Audio 轻量压缩 (Phase 2 论文防守)
            dict(name='--use_audio_light_pruning',
                 default=False,
                 type=str2bool,
                 help='Whether to use audio light filtering (low_conf or top_r)'),
            dict(name='--audio_filter_mode',
                 default='top_r',
                 type=str,
                 help='Audio filter: low_conf or top_r'),
            dict(name='--audio_retain_ratio',
                 default=0.5,
                 type=float,
                 help='Audio top-r retention ratio (when mode=top_r)'),
            dict(name='--audio_keep_ratio',
                 default=0.50,
                 type=float,
                 help='Audio keep ratio (alias for top-r, deterministic)'),
            dict(name='--audio_rel_threshold',
                 default=0.3,
                 type=float,
                 help='Audio low-confidence threshold (when mode=low_conf)'),
            dict(name='--audio_min_retain',
                 default=10,
                 type=int,
                 help='Minimum audio frames to retain per sample'),
            # 冲突度量可替换 (Phase 2 消融 JS vs KL)
            dict(name='--conflict_metric',
                 default='js',
                 type=str,
                 help='Conflict divergence: js or kl'),
            dict(name='--use_alignment_ref',
                 default=True,
                 type=str2bool,
                 help='Use alignment-aware conflict reference'),
            # P2 招1 招2: 边界敏感头 + 排序损失
            dict(name='--use_polarity_head',
                 default=False,
                 type=str2bool,
                 help='P2: Boundary-sensitive polarity head for Acc-2/F1'),
            dict(name='--lambda_cls',
                 default=0.1,
                 type=float,
                 help='Weight for polarity BCE loss'),
            dict(name='--polar_delta',
                 default=1.0,
                 type=float,
                 help='Weight w(y)=min(1,|y|/delta) for polarity loss, plan default 1.0'),
            dict(name='--lambda_rank',
                 default=0.05,
                 type=float,
                 help='Weight for ranking loss (fixed enabled per plan)'),
            dict(name='--rank_margin',
                 default=0.2,
                 type=float,
                 help='Margin for ranking loss, plan default 0.2'),
            dict(name='--ranking_threshold',
                 default=0.1,
                 type=float,
                 help='Pairwise ranking: only use pairs with y_i-y_j > threshold to avoid noisy pairs; 0=all pairs'),
            dict(name='--use_dynamic_margin_rank',
                 default=True,
                 type=str2bool,
                 help='Use dynamic margin: gamma*(y_i-y_j) instead of fixed rank_margin; CrossSent-style, reduces conflict with MAE'),
            dict(name='--rank_margin_gamma',
                 default=0.4,
                 type=float,
                 help='Dynamic margin scaling: margin=gamma*(y_i-y_j), 0.4~0.6; lower reduces overfitting from ranking'),
            dict(name='--use_grcf',
                 default=False,
                 type=str2bool,
                 help='Two-stage GRCF: Stage1 ranking-dominant, Stage2 freeze backbone + MAE-only calibration'),
            dict(name='--grcf_stage1_epochs',
                 default=40,
                 type=int,
                 help='GRCF Stage1 epochs (ranking); Stage2 = n_epochs - grcf_stage1_epochs'),
            dict(name='--grcf_stage1_regression_weight',
                 default=0.1,
                 type=float,
                 help='Scale for loss_re in Stage1; <1 to focus on ranking, 0=ranking-only'),
            # PID + 对比解耦 (重构架构)
            dict(name='--pid_K',
                 default=16,
                 type=int,
                 help='Bins K for PID joint distribution'),
            dict(name='--sinkhorn_iters',
                 default=5,
                 type=int,
                 help='Sinkhorn iterations for PID'),
            dict(name='--use_batch_pid_prior',
                 default=False,
                 type=str2bool,
                 help='Route B: use BatchPIDPrior (EMA r/s global prior); only when model_type=pid_dualpath'),
            dict(name='--use_pairwise_joint_path',
                 default=True,
                 type=str2bool,
                 help='Route B: JointGainPath use pairwise TA/TV/AV cross-attention; False = simple Transformer'),
            dict(name='--use_residual_gate_in_joint_path',
                 default=False,
                 type=str2bool,
                 help='Route B: apply residual gate g_s in JointGainPath'),
            dict(name='--router_tau',
                 default=0.5,
                 type=float,
                 help='Route B: softmax temperature for alpha_r/alpha_s; smaller = sharper routing (default 0.5 so Synergy/R can diverge)'),
            dict(name='--path_layers',
                 default=2,
                 type=int,
                 help='Route B: Transformer 层数，SharedPath 与 JointGainPath 共用；论文 Table 2 CH-SIMS Dynamic Transformer Block=3，可试 3'),
            dict(name='--path_nhead',
                 default=4,
                 type=int,
                 help='Route B: Transformer attention heads，SharedPath 与 JointGainPath 共用'),
            dict(name='--freeze_bert',
                 default=False,
                 type=str2bool,
                 help='冻结 BERT 全部参数（只训练后续模块）；适合小数据集（如 CH-SIMS 1368 样本）防止 BERT 全量微调过拟合'),
            dict(name='--freeze_vision_audio',
                 default=False,
                 type=str2bool,
                 help='冻结视觉/音频单模态编码器（enc_v/enc_a），与原 KuDA 一致：只训融合+预测；与 freeze_bert 同开可完全对齐原 KuDA 设定'),
            dict(name='--bert_lr',
                 default=2e-5,
                 type=float,
                 help='BERT 单独学习率（0 表示与主 lr 相同）；建议小数据集用 1e-5~2e-5，比 main lr 小一个量级以防 BERT 过拟合'),
            dict(name='--lambda_alpha_var',
                 default=0.05,
                 type=float,
                 help='Route B: weight for encouraging batch variance of alpha_s so synergy path is used unevenly'),
            dict(name='--return_pairwise_debug',
                 default=False,
                 type=str2bool,
                 help='Route B: when True, forward returns F_TA, F_TV, F_AV in dict for analysis'),
            dict(name='--debug_joint_path',
                 default=False,
                 type=str2bool,
                 help='Route B: print shape debug in JointGainPath forward'),
            dict(name='--lambda_pid',
                 default=0.3,
                 type=float,
                 help='Weight for L_PID (larger to avoid synergy collapse)'),
            dict(name='--pid_lr',
                 default=5e-4,
                 type=float,
                 help='Learning rate for PID estimator (higher than main lr)'),
            dict(name='--lambda_S_var',
                 default=0.1,
                 type=float,
                 help='Weight for L_S_var: maximize batch variance of S to activate synergy'),
            dict(name='--lambda_S_diverse',
                 default=0.15,
                 type=float,
                 help='Weight for L_S_diverse: soft target from sample error so S spreads (high error->high S)'),
            dict(name='--sigmoid_scale',
                 default=2.0,
                 type=float,
                 help='Sigmoid scale in PID S = sigmoid(ratio*sigmoid_scale), larger = steeper'),
            dict(name='--lambda_S_weight',
                 default=0.0,
                 type=float,
                 help='Route B: gamma for S-based sample reweighting, w_i=1+gamma*(S_mean-S_i), 0=off'),
            dict(name='--lambda_S_weight_mix',
                 default=0.5,
                 type=float,
                 help='Route B: mix alpha for loss = alpha*weighted_mae + (1-alpha)*mae when lambda_S_weight>0'),
            dict(name='--lambda_diff',
                 default=0.15,
                 type=float,
                 help='Weight for L_diff (margin push + optional InfoNCE)'),
            dict(name='--lambda_nce_diff',
                 default=0.05,
                 type=float,
                 help='Weight for InfoNCE pull (high-S F_conf)'),
            dict(name='--nce_tau',
                 default=0.07,
                 type=float,
                 help='Temperature for InfoNCE'),
            dict(name='--lambda_classification',
                 default=0.35,
                 type=float,
                 help='Weight for L_classification (BCE, binary from continuous: >0 pos), λ2 in L_total; try 0.3~0.4 to boost F1'),
            dict(name='--cls_pos_weight',
                 default=1.0,
                 type=float,
                 help='BCE pos_weight for binary head (positive class); >1 when pos samples fewer, to boost F1'),
            dict(name='--lambda_aux',
                 default=0.1,
                 type=float,
                 help='Route B: weight for dual-path auxiliary loss (alpha_r*L_R + alpha_s*L_S)'),
            dict(name='--lambda_ortho',
                 default=0.005,
                 type=float,
                 help='Weight for F_cons/F_conf orthogonality'),
            dict(name='--lambda_extreme',
                 default=0.0,
                 type=float,
                 help='对极端样本(|y|大)加权: w=1+lambda_extreme*|y|，主回归损失按w加权；>0时启用，缓解预测向0收缩'),
            dict(name='--margin',
                 default=0.5,
                 type=float,
                 help='Margin for L_push (F_conf vs F_cons)'),
            dict(name='--s_high_threshold',
                 default=0.5,
                 type=float,
                 help='Threshold for high synergy (optional)'),
            dict(name='--pid_warmup_epochs',
                 default=0,
                 type=int,
                 help='Linear warmup for aux_pid/L_ortho/L_rank etc. 0=disable, only pid_prior_warmup_epochs cold-start applies'),
            dict(name='--tau_evidence_min',
                 default=0.1,
                 type=float,
                 help='Minimum temperature for token-level evidence softmax during early epochs'),
            dict(name='--tau_evidence_warmup_ratio',
                 default=0.3,
                 type=float,
                 help='Fraction of total epochs used to anneal evidence temperature from tau_evidence_min to 1.0'),
            dict(name='--pid_prior_warmup_epochs',
                 default=3,
                 type=int,
                 help='Warm-up epochs for BatchPIDPrior EMA: freeze r_global/s_global and use neutral 0.5 prior'),
            dict(name='--curriculum_enable',
                 default=True,
                 type=str2bool,
                 help='Enable three-stage curriculum for Route B losses'),
            dict(name='--curriculum_stage1_epochs',
                 default=15,
                 type=int,
                 help='Epoch boundary N for curriculum stage 1 (feature baseline)'),
            dict(name='--curriculum_stage2_epochs',
                 default=25,
                 type=int,
                 help='Epoch boundary M for curriculum stage 2 (ranking alignment); stage3 starts from M+1'),
            dict(name='--lambda_task_stage1',
                 default=0.05,
                 type=float,
                 help='Relative weight scale for main regression loss in curriculum stage 1'),
            dict(name='--lambda_task_stage2',
                 default=0.5,
                 type=float,
                 help='Relative weight scale for main regression loss in curriculum stage 2'),
            dict(name='--lambda_rank_stage2_scale',
                 default=1.2,
                 type=float,
                 help='Additional scale on lambda_rank during curriculum stage 2'),
            dict(name='--ortho_epsilon',
                 default=0.15,
                 type=float,
                 help='L_ortho truncation: only penalize when |cos_sim| > epsilon; 0.1~0.2 prevents over-decoupling'),
            dict(name='--curriculum_stage3_ramp_epochs',
                 default=5,
                 type=int,
                 help='Epochs to linearly ramp lambda_task from stage2 value to 1.0 in stage 3'),
            # 消融实验开关（默认 False，不影响原方案复现）
            dict(name='--ablation_no_pid_routing',
                 action='store_true',
                 help='Ablation: w/o PID Routing. S fixed 0.5, F_fusion=0.5*F_cons+0.5*F_conf, L_PID=0'),
            dict(name='--ablation_single_branch',
                 action='store_true',
                 help='Ablation: w/o Dual-Branch. F_fusion=F_cons only, lambda_diff/ortho/nce_diff forced 0'),
        ],

        'common': [
            dict(name='--seed',  # try different seeds
                 default=2024,
                 type=int),
            dict(name='--batch_size',
                 default=32,
                 type=int,
                 help=' '),
            dict(name='--lr',
                 type=float,
                 default=1e-4),
            dict(name='--grad_clip',
                 type=float,
                 default=1.0,
                 help='Max gradient norm for clipping; 0 = disable'),
            dict(name='--weight_decay',
                 type=float,
                 default=0.05),
            dict(name='--loss_fn',
                 type=str,
                 default='smoothl1',
                 help='任务回归损失：smoothl1（Huber, default）| l1（直接最小化 MAE，适合压 MAE 指标）| mse'),
            dict(name='--n_epochs',
                 default=100,
                 type=int,
                 help='Number of total epochs to run'),
            dict(name='--early_stop_patience',
                 default=5,
                 type=int,
                 help='Early stop if no test MAE improvement for this many epochs (0=disable)'),
            dict(name='--early_stop_min_epochs',
                 default=25,
                 type=int,
                 help='Early stopping will not trigger before this epoch'),
            dict(name='--log_path',
                 default='./log/',
                 type=str,
                 help='the logger path for save options and experience results'),
            dict(name='--no_save_model',
                 default=False,
                 type=str2bool,
                 help='不保存 best.pth/best_corr.pth，仅保留 summary.json、valid_curve.csv、日志；适合超参扫描省磁盘'),
            dict(name='--checkpoint_dir',
                 default='',
                 type=str,
                 help='Override checkpoint save directory (default: ./checkpoints/{DATASET})'),
            dict(name='--checkpoint_path',
                 default='',
                 type=str,
                 help='Path to load checkpoint for eval/calibration (e.g. ./checkpoints/full_IEC+ICR_full/best.pth); empty = default SIMS path)'),
            dict(name='--resume',
                 default='',
                 type=str,
                 help='Path to best.pth to resume training (e.g. ./checkpoints/sweep_round2/r2_c6/best.pth); will train from epoch+1 to n_epochs'),
            dict(name='--use_cmvn',
                 default=True,
                 type=str2bool,
                 help='Whether to apply CMVN normalization to audio features'),
            # Phase 2: 控制flags
            dict(name='--use_conflict_js',
                 default=False,
                 type=str2bool,
                 help='Whether to use Conflict-JS module (Phase 2)'),
            dict(name='--use_routing',
                 default=True,
                 type=str2bool,
                 help='Whether to use conflict-driven routing (Phase 2)'),
            dict(name='--lambda_nce',
                 default=0.1,
                 type=float,
                 help='Weight for NCE contrastive loss'),
            dict(name='--lambda_senti',
                 default=0.05,
                 type=float,
                 help='Weight for SentimentProjector auxiliary loss'),
            dict(name='--lambda_js',
                 default=0.12,
                 type=float,
                 help='Weight for JS divergence regularization loss (Step2: 0.1->0.12 加强冲突正则化)'),
            dict(name='--lambda_con',
                 default=0.03,
                 type=float,
                 help='Weight for congruent consistency loss'),
            dict(name='--lambda_cal',
                 default=0.03,
                 type=float,
                 help='Weight for calibration loss'),
            dict(name='--lambda_align',
                 default=0.1,
                 type=float,
                 help='Weight for C-D alignment MSE term inside calibration loss (L_align)'),
            dict(name='--align_to_d_tv_only',
                 default=False,
                 type=str2bool,
                 help='When True, use D_TV (text-vision) only for L_align instead of D_all (SIMS)'),
            dict(name='--freeze_conflict_js',
                 default=False,
                 type=str2bool,
                 help='Phase3: freeze ConflictJS and SentimentProjector, only fine-tune pruner+fusion')
        ]
    }

    for group in arguments.values():
        for argument in group:
            name = argument['name']
            del argument['name']
            parser.add_argument(name, **argument)

    args = parser.parse_args()
    return args
