import argparse


def str2bool(v):
    if isinstance(v, bool):
        return v
    v = str(v).strip().lower()
    if v in ('true', '1', 'yes', 'y', 't'):
        return True
    if v in ('false', '0', 'no', 'n', 'f'):
        return False
    raise argparse.ArgumentTypeError(f"Invalid boolean value: {v}")


def parse_opts():
    parser = argparse.ArgumentParser()
    arguments = {
        'dataset': [
            dict(name='--datasetName',
                 type=str,
                 default='sims',
                 help='mosi, mosei, sims or simsv2'),
            dict(name='--dataPath',
                 default="/18T/yechenlu/MSA_datasets/SIMS-v2/ch-sims2s/unaligned.pkl",
                 type=str,
                 help=' '),
            dict(name='--seq_lens',
                 default=[50, 55, 400],
                 type=list,
                 help='the length of T, V, A modalities; sims/simsv2: [50, 55, 400] (text from BERT len); mosi/mosei: []'),
            dict(name='--fea_dims',
                 default=[768, 177, 25],
                 type=list,
                 help='feature dims of T, V, A; sims/simsv2: [768, 177, 25]; mosi/mosei: [768, 709, 33]'),
            dict(name='--num_workers',
                 default=8,
                 type=int,
                 help=' '),
            dict(name='--train_mode',
                 default="regression",
                 type=str,
                 help=' '),
        ],

        'network': [
            dict(name='--fusion_layers',
                 default=3,
                 type=int),
            dict(name='--dropout',
                 default=0.3,
                 type=float),
            dict(name='--hidden_size',
                 default=256,
                 type=int),
            dict(name='--ffn_size',
                 default=512,
                 type=int),
            # Phase 2: Conflict-JS参数
            dict(name='--senti_num_classes',
                 default=7,
                 type=int,
                 help='Number of sentiment classes for posterior distribution'),
            dict(name='--tau_conf',
                 default=0.3,
                 type=float,
                 help='Threshold for conflict evidence (sentiment difference)'),
            dict(name='--tau_con',
                 default=0.1,
                 type=float,
                 help='Threshold for congruent evidence (sentiment difference)'),
            dict(name='--tau_rel',
                 default=0.5,
                 type=float,
                 help='Threshold for confidence (reliability)'),
            dict(name='--rel_min',
                 default=0.20,
                 type=float,
                 help='Minimum reliability for valid tokens in EvidenceSplitter'),
            dict(name='--conf_ratio',
                 default=0.25,
                 type=float,
                 help='Conflict evidence percentile (top conf_ratio)'),
            dict(name='--con_ratio',
                 default=0.25,
                 type=float,
                 help='Congruent evidence percentile (bottom con_ratio)'),
            dict(name='--gate_k',
                 default=10.0,
                 type=float,
                 help='Gate gain for alpha_m'),
            dict(name='--gate_tau',
                 default=0.15,
                 type=float,
                 help='Gate threshold for conflict routing'),
            # Token筛选参数
            dict(name='--use_vision_pruning',
                 default=True,
                 type=str2bool,
                 help='Whether to use vision token pruning'),
            dict(name='--iec_mode',
                 default='text_guided',
                 type=str,
                 help='IEC mode: text_guided (prune+merge) or heuristic (DART)'),
            dict(name='--vision_keep_ratio',
                 default=0.50,
                 type=float,
                 help='Vision token keep ratio for TextGuidedPruner'),
            dict(name='--vision_target_ratio',
                 default=0.6,
                 type=float,
                 help='Vision token retention ratio (heuristic mode)'),
            # Audio 轻量压缩 (Phase 2 论文防守)
            dict(name='--use_audio_light_pruning',
                 default=False,
                 type=str2bool,
                 help='Whether to use audio light filtering (low_conf or top_r)'),
            dict(name='--audio_filter_mode',
                 default='top_r',
                 type=str,
                 help='Audio filter: low_conf or top_r'),
            dict(name='--audio_retain_ratio',
                 default=0.5,
                 type=float,
                 help='Audio top-r retention ratio (when mode=top_r)'),
            dict(name='--audio_keep_ratio',
                 default=0.50,
                 type=float,
                 help='Audio keep ratio (alias for top-r, deterministic)'),
            dict(name='--audio_rel_threshold',
                 default=0.3,
                 type=float,
                 help='Audio low-confidence threshold (when mode=low_conf)'),
            dict(name='--audio_min_retain',
                 default=10,
                 type=int,
                 help='Minimum audio frames to retain per sample'),
            # 冲突度量可替换 (Phase 2 消融 JS vs KL)
            dict(name='--conflict_metric',
                 default='js',
                 type=str,
                 help='Conflict divergence: js or kl'),
            dict(name='--use_alignment_ref',
                 default=True,
                 type=str2bool,
                 help='Use alignment-aware conflict reference'),
            # P2 招1 招2: 边界敏感头 + 排序损失
            dict(name='--use_polarity_head',
                 default=False,
                 type=str2bool,
                 help='P2: Boundary-sensitive polarity head for Acc-2/F1'),
            dict(name='--lambda_cls',
                 default=0.1,
                 type=float,
                 help='Weight for polarity BCE loss'),
            dict(name='--polar_delta',
                 default=1.0,
                 type=float,
                 help='Weight w(y)=min(1,|y|/delta) for polarity loss, plan default 1.0'),
            dict(name='--lambda_rank',
                 default=0.05,
                 type=float,
                 help='Weight for ranking loss (fixed enabled per plan)'),
            dict(name='--rank_margin',
                 default=0.2,
                 type=float,
                 help='Margin for ranking loss, plan default 0.2'),
        ],

        'common': [
            dict(name='--seed',  # try different seeds
                 default=1111,
                 type=int),
            dict(name='--batch_size',
                 default=32,
                 type=int,
                 help=' '),
            dict(name='--lr',
                 type=float,
                 default=3e-5),
            dict(name='--weight_decay',
                 type=float,
                 default=1e-5),
            dict(name='--n_epochs',
                 default=50,
                 type=int,
                 help='Number of total epochs to run'),
            dict(name='--log_path',
                 default='./log/',
                 type=str,
                 help='the logger path for save options and experience results'),
            dict(name='--checkpoint_dir',
                 default='',
                 type=str,
                 help='Override checkpoint save directory (default: ./checkpoints/{DATASET})'),
            # Phase 1: 新增参数
            dict(name='--use_ki',
                 default=False,
                 type=str2bool,
                 help='Whether to use knowledge injection pretraining weights'),
            dict(name='--use_cmvn',
                 default=True,
                 type=str2bool,
                 help='Whether to apply CMVN normalization to audio features'),
            # Phase 2: 控制flags
            dict(name='--use_conflict_js',
                 default=False,
                 type=str2bool,
                 help='Whether to use Conflict-JS module (Phase 2)'),
            dict(name='--use_routing',
                 default=True,
                 type=str2bool,
                 help='Whether to use conflict-driven routing (Phase 2)'),
            dict(name='--lambda_nce',
                 default=0.1,
                 type=float,
                 help='Weight for NCE contrastive loss'),
            dict(name='--lambda_senti',
                 default=0.05,
                 type=float,
                 help='Weight for SentimentProjector auxiliary loss'),
            dict(name='--lambda_js',
                 default=0.1,
                 type=float,
                 help='Weight for JS divergence regularization loss'),
            dict(name='--lambda_con',
                 default=0.1,
                 type=float,
                 help='Weight for congruent consistency loss'),
            dict(name='--lambda_cal',
                 default=0.1,
                 type=float,
                 help='Weight for calibration loss'),
            dict(name='--freeze_conflict_js',
                 default=False,
                 type=str2bool,
                 help='Phase3: freeze ConflictJS and SentimentProjector, only fine-tune pruner+fusion')
        ]
    }

    for group in arguments.values():
        for argument in group:
            name = argument['name']
            del argument['name']
            parser.add_argument(name, **argument)

    args = parser.parse_args()
    return args
