import argparse


def str2bool(v):
    if isinstance(v, bool):
        return v
    v = str(v).strip().lower()
    if v in ('true', '1', 'yes', 'y', 't'):
        return True
    if v in ('false', '0', 'no', 'n', 'f'):
        return False
    raise argparse.ArgumentTypeError(f"Invalid boolean value: {v}")


def parse_opts():
    parser = argparse.ArgumentParser()
    arguments = {
        'dataset': [
            dict(name='--datasetName',
                 type=str,
                 default='sims',
                 help='mosi, mosei, sims or simsv2'),
            dict(name='--dataPath',
                 default="/18T/yechenlu/MSA_datasets/SIMS/Processed/unaligned_39.pkl",
                 type=str,
                 help=' '),
            dict(name='--seq_lens',
                 default=[50, 55, 400],
                 type=list,
                 help='the length of T, V, A modalities; sims/simsv2: [50, 55, 400] (text from BERT len); mosi/mosei: []'),
            dict(name='--fea_dims',
                 default=[768, 177, 25],
                 type=list,
                 help='feature dims of T, V, A; sims/simsv2: [768, 177, 25]; mosi/mosei: [768, 709, 33]'),
            dict(name='--num_workers',
                 default=8,
                 type=int,
                 help=' '),
            dict(name='--train_mode',
                 default="regression",
                 type=str,
                 help=' '),
        ],

        'network': [
            dict(name='--model_type',
                 default='kmsa',
                 type=str,
                 help='Model: kmsa (default) or pid_dualpath for Route B dual-path'),
            dict(name='--fusion_layers',
                 default=3,
                 type=int),
            dict(name='--dropout',
                 default=0.4,
                 type=float),
            dict(name='--hidden_size',
                 default=256,
                 type=int),
            dict(name='--ffn_size',
                 default=512,
                 type=int),
            # Phase 2: Conflict-JS参数
            dict(name='--senti_num_classes',
                 default=7,
                 type=int,
                 help='Number of sentiment classes for posterior distribution'),
            dict(name='--tau_conf',
                 default=0.3,
                 type=float,
                 help='Threshold for conflict evidence (sentiment difference)'),
            dict(name='--tau_con',
                 default=0.1,
                 type=float,
                 help='Threshold for congruent evidence (sentiment difference)'),
            dict(name='--tau_rel',
                 default=0.5,
                 type=float,
                 help='Threshold for confidence (reliability)'),
            dict(name='--rel_min',
                 default=0.05,
                 type=float,
                 help='Minimum reliability for valid tokens in EvidenceSplitter'),
            dict(name='--conf_ratio',
                 default=0.25,
                 type=float,
                 help='Conflict evidence percentile (top conf_ratio)'),
            dict(name='--con_ratio',
                 default=0.25,
                 type=float,
                 help='Congruent evidence percentile (bottom con_ratio)'),
            dict(name='--evidence_split_mode',
                 default='topk',
                 type=str,
                 help='EvidenceSplitter strategy: topk (quota by d) or quantile (original)'),
            dict(name='--min_conf_k',
                 default=4,
                 type=int,
                 help='Min number of conflict tokens per sample in topk mode'),
            dict(name='--min_con_k',
                 default=4,
                 type=int,
                 help='Min number of congruent tokens per sample in topk mode'),
            dict(name='--gate_k',
                 default=8.0,
                 type=float,
                 help='Gate gain for alpha_m (Step2: 10.0->8.0 使门控更平滑)'),
            dict(name='--gate_tau',
                 default=0.12,
                 type=float,
                 help='Gate threshold for conflict routing (Step2: 0.15->0.12 更容易触发冲突分支)'),
            # Token筛选参数
            dict(name='--use_vision_pruning',
                 default=True,
                 type=str2bool,
                 help='Whether to use vision token pruning'),
            dict(name='--iec_mode',
                 default='text_guided',
                 type=str,
                 help='IEC mode: text_guided (prune+merge) or heuristic (DART)'),
            dict(name='--vision_keep_ratio',
                 default=0.50,
                 type=float,
                 help='Vision token keep ratio for TextGuidedPruner'),
            dict(name='--vision_target_ratio',
                 default=0.6,
                 type=float,
                 help='Vision token retention ratio (heuristic mode)'),
            # Audio 轻量压缩 (Phase 2 论文防守)
            dict(name='--use_audio_light_pruning',
                 default=False,
                 type=str2bool,
                 help='Whether to use audio light filtering (low_conf or top_r)'),
            dict(name='--audio_filter_mode',
                 default='top_r',
                 type=str,
                 help='Audio filter: low_conf or top_r'),
            dict(name='--audio_retain_ratio',
                 default=0.5,
                 type=float,
                 help='Audio top-r retention ratio (when mode=top_r)'),
            dict(name='--audio_keep_ratio',
                 default=0.50,
                 type=float,
                 help='Audio keep ratio (alias for top-r, deterministic)'),
            dict(name='--audio_rel_threshold',
                 default=0.3,
                 type=float,
                 help='Audio low-confidence threshold (when mode=low_conf)'),
            dict(name='--audio_min_retain',
                 default=10,
                 type=int,
                 help='Minimum audio frames to retain per sample'),
            # 冲突度量可替换 (Phase 2 消融 JS vs KL)
            dict(name='--conflict_metric',
                 default='js',
                 type=str,
                 help='Conflict divergence: js or kl'),
            dict(name='--use_alignment_ref',
                 default=True,
                 type=str2bool,
                 help='Use alignment-aware conflict reference'),
            # P2 招1 招2: 边界敏感头 + 排序损失
            dict(name='--use_polarity_head',
                 default=False,
                 type=str2bool,
                 help='P2: Boundary-sensitive polarity head for Acc-2/F1'),
            dict(name='--lambda_cls',
                 default=0.1,
                 type=float,
                 help='Weight for polarity BCE loss'),
            dict(name='--polar_delta',
                 default=1.0,
                 type=float,
                 help='Weight w(y)=min(1,|y|/delta) for polarity loss, plan default 1.0'),
            dict(name='--lambda_rank',
                 default=0.05,
                 type=float,
                 help='Weight for ranking loss (fixed enabled per plan)'),
            dict(name='--rank_margin',
                 default=0.2,
                 type=float,
                 help='Margin for ranking loss, plan default 0.2'),
            # PID + 对比解耦 (重构架构)
            dict(name='--pid_K',
                 default=16,
                 type=int,
                 help='Bins K for PID joint distribution'),
            dict(name='--sinkhorn_iters',
                 default=5,
                 type=int,
                 help='Sinkhorn iterations for PID'),
            dict(name='--use_batch_pid_prior',
                 default=False,
                 type=str2bool,
                 help='Route B: use BatchPIDPrior (EMA r/s global prior); only when model_type=pid_dualpath'),
            dict(name='--use_pairwise_joint_path',
                 default=True,
                 type=str2bool,
                 help='Route B: JointGainPath use pairwise TA/TV/AV cross-attention; False = simple Transformer'),
            dict(name='--use_residual_gate_in_joint_path',
                 default=True,
                 type=str2bool,
                 help='Route B: apply residual gate g_s in JointGainPath'),
            dict(name='--router_tau',
                 default=0.5,
                 type=float,
                 help='Route B: softmax temperature for alpha_r/alpha_s; smaller = sharper routing (default 0.5 so Synergy/R can diverge)'),
            dict(name='--path_layers',
                 default=2,
                 type=int,
                 help='Route B: Transformer 层数，SharedPath 与 JointGainPath 共用；论文 Table 2 CH-SIMS Dynamic Transformer Block=3，可试 3'),
            dict(name='--path_nhead',
                 default=4,
                 type=int,
                 help='Route B: Transformer attention heads，SharedPath 与 JointGainPath 共用'),
            dict(name='--lambda_alpha_var',
                 default=0.05,
                 type=float,
                 help='Route B: weight for encouraging batch variance of alpha_s so synergy path is used unevenly'),
            dict(name='--return_pairwise_debug',
                 default=False,
                 type=str2bool,
                 help='Route B: when True, forward returns F_TA, F_TV, F_AV in dict for analysis'),
            dict(name='--debug_joint_path',
                 default=False,
                 type=str2bool,
                 help='Route B: print shape debug in JointGainPath forward'),
            dict(name='--lambda_pid',
                 default=0.3,
                 type=float,
                 help='Weight for L_PID (larger to avoid synergy collapse)'),
            dict(name='--pid_lr',
                 default=5e-4,
                 type=float,
                 help='Learning rate for PID estimator (higher than main lr)'),
            dict(name='--lambda_S_var',
                 default=0.1,
                 type=float,
                 help='Weight for L_S_var: maximize batch variance of S to activate synergy'),
            dict(name='--lambda_S_diverse',
                 default=0.15,
                 type=float,
                 help='Weight for L_S_diverse: soft target from sample error so S spreads (high error->high S)'),
            dict(name='--sigmoid_scale',
                 default=2.0,
                 type=float,
                 help='Sigmoid scale in PID S = sigmoid(ratio*sigmoid_scale), larger = steeper'),
            dict(name='--lambda_diff',
                 default=0.15,
                 type=float,
                 help='Weight for L_diff (margin push + optional InfoNCE)'),
            dict(name='--lambda_nce_diff',
                 default=0.05,
                 type=float,
                 help='Weight for InfoNCE pull (high-S F_conf)'),
            dict(name='--nce_tau',
                 default=0.07,
                 type=float,
                 help='Temperature for InfoNCE'),
            dict(name='--lambda_classification',
                 default=0.35,
                 type=float,
                 help='Weight for L_classification (BCE, binary from continuous: >0 pos), λ2 in L_total; try 0.3~0.4 to boost F1'),
            dict(name='--cls_pos_weight',
                 default=1.0,
                 type=float,
                 help='BCE pos_weight for binary head (positive class); >1 when pos samples fewer, to boost F1'),
            dict(name='--lambda_aux',
                 default=0.1,
                 type=float,
                 help='Route B: weight for dual-path auxiliary loss (alpha_r*L_R + alpha_s*L_S)'),
            dict(name='--lambda_ortho',
                 default=0.005,
                 type=float,
                 help='Weight for F_cons/F_conf orthogonality'),
            dict(name='--margin',
                 default=0.5,
                 type=float,
                 help='Margin for L_push (F_conf vs F_cons)'),
            dict(name='--s_high_threshold',
                 default=0.5,
                 type=float,
                 help='Threshold for high synergy (optional)'),
            dict(name='--pid_warmup_epochs',
                 default=2,
                 type=int,
                 help='Linear warmup epochs for PID/contrastive (0 or 2 to avoid S frozen at 0)'),
            # 消融实验开关（默认 False，不影响原方案复现）
            dict(name='--ablation_no_pid_routing',
                 action='store_true',
                 help='Ablation: w/o PID Routing. S fixed 0.5, F_fusion=0.5*F_cons+0.5*F_conf, L_PID=0'),
            dict(name='--ablation_single_branch',
                 action='store_true',
                 help='Ablation: w/o Dual-Branch. F_fusion=F_cons only, lambda_diff/ortho/nce_diff forced 0'),
        ],

        'common': [
            dict(name='--seed',  # try different seeds
                 default=1111,
                 type=int),
            dict(name='--batch_size',
                 default=32,
                 type=int,
                 help=' '),
            dict(name='--lr',
                 type=float,
                 default=5e-5),
            dict(name='--grad_clip',
                 type=float,
                 default=1.0,
                 help='Max gradient norm for clipping; 0 = disable'),
            dict(name='--weight_decay',
                 type=float,
                 default=1e-4),
            dict(name='--n_epochs',
                 default=80,
                 type=int,
                 help='Number of total epochs to run'),
            dict(name='--log_path',
                 default='./log/',
                 type=str,
                 help='the logger path for save options and experience results'),
            dict(name='--checkpoint_dir',
                 default='',
                 type=str,
                 help='Override checkpoint save directory (default: ./checkpoints/{DATASET})'),
            dict(name='--checkpoint_path',
                 default='',
                 type=str,
                 help='Path to load checkpoint for eval/calibration (e.g. ./checkpoints/full_IEC+ICR_full/best.pth); empty = default SIMS path)'),
            dict(name='--resume',
                 default='',
                 type=str,
                 help='Path to best.pth to resume training (e.g. ./checkpoints/sweep_round2/r2_c6/best.pth); will train from epoch+1 to n_epochs'),
            dict(name='--use_cmvn',
                 default=True,
                 type=str2bool,
                 help='Whether to apply CMVN normalization to audio features'),
            # Phase 2: 控制flags
            dict(name='--use_conflict_js',
                 default=False,
                 type=str2bool,
                 help='Whether to use Conflict-JS module (Phase 2)'),
            dict(name='--use_routing',
                 default=True,
                 type=str2bool,
                 help='Whether to use conflict-driven routing (Phase 2)'),
            dict(name='--lambda_nce',
                 default=0.1,
                 type=float,
                 help='Weight for NCE contrastive loss'),
            dict(name='--lambda_senti',
                 default=0.05,
                 type=float,
                 help='Weight for SentimentProjector auxiliary loss'),
            dict(name='--lambda_js',
                 default=0.12,
                 type=float,
                 help='Weight for JS divergence regularization loss (Step2: 0.1->0.12 加强冲突正则化)'),
            dict(name='--lambda_con',
                 default=0.03,
                 type=float,
                 help='Weight for congruent consistency loss'),
            dict(name='--lambda_cal',
                 default=0.03,
                 type=float,
                 help='Weight for calibration loss'),
            dict(name='--lambda_align',
                 default=0.1,
                 type=float,
                 help='Weight for C-D alignment MSE term inside calibration loss (L_align)'),
            dict(name='--align_to_d_tv_only',
                 default=False,
                 type=str2bool,
                 help='When True, use D_TV (text-vision) only for L_align instead of D_all (SIMS)'),
            dict(name='--freeze_conflict_js',
                 default=False,
                 type=str2bool,
                 help='Phase3: freeze ConflictJS and SentimentProjector, only fine-tune pruner+fusion')
        ]
    }

    for group in arguments.values():
        for argument in group:
            name = argument['name']
            del argument['name']
            parser.add_argument(name, **argument)

    args = parser.parse_args()
    return args
